In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/jigsawlabs-student/pytorch-intro-curriculum/main/5-training-mathematically/cell_multiple.csv"
df = pd.read_csv(url)

In [2]:
df[:2]

mean_area  mean_concavity  is_cancerous
0      1.001          0.3001             1
1      1.326          0.0869             1

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['mean_area'].plot(kind='hist', bins=20, title='mean_area')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['mean_concavity'].plot(kind='hist', bins=20, title='mean_concavity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='mean_area', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='mean_area', y='mean_concavity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['mean_concavity']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('mean_concavity')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['mean_area']
  ys = series['mean_concavity']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('mean_area', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('mean_area')
_ = plt.ylabel('mean_concavity')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['mean_area']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'mean_area'}, axis=1)
              .sort_values('mean_area', ascending=True))
  xs = counted['mean_area']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('mean_area', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('mean_area')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_9['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['mean_area'].plot(kind='line', figsize=(8, 4), title='mean_area')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_11['mean_concavity'].plot(kind='line', figsize=(8, 4), title='mean_concavity')
plt.gca().spines[['top', 'right']].set_visible(False)

In [3]:
import torch
X_tensor = torch.tensor(df[['mean_area', 'mean_concavity']].values).float()
y_tensor = torch.tensor(df['is_cancerous']).float()

In [4]:
first_x = X_tensor[0]
first_y = y_tensor[0]

first_x, first_y

(tensor([1.0010, 0.3001]), tensor(1.))

In [5]:
def linear_fn(x, w, b):
    return x @ w + b

In [6]:
def activation_fn(z):
    return torch.sigmoid(z)

In [7]:
w = torch.tensor([.5, .3]).float()
b = torch.tensor(-2.).float()

In [8]:
z = linear_fn(first_x, w, b)
z

tensor(-1.4095)

In [9]:
y_hat = activation_fn(z)
y_hat

tensor(0.1963)

In [11]:
import torch
def delta_J_delta_sigma(y_hat, y):
    return torch.sum(2*(y_hat - y))
def delta_sigma_delta(z):
    return torch.sigmoid(z)*(1 - torch.sigmoid(z))
def delta_z_delta_w(x):
    return x
def delta_z_delta_b():
    return 1

In [12]:
w_grad = delta_z_delta_w(first_x)*delta_sigma_delta(z)*delta_J_delta_sigma(y_hat, first_y)
w_grad

tensor([-0.2539, -0.0761])

In [13]:
b_grad = delta_z_delta_b()*delta_sigma_delta(z)*delta_J_delta_sigma(y_hat, first_y)
b_grad

tensor(-0.2536)

In [14]:
dj_dsig = delta_J_delta_sigma(y_hat, first_y)
dj_dsig

tensor(-1.6074)

In [15]:
dsig_dz = delta_sigma_delta(z)
dz_dJ = dsig_dz*dj_dsig
dz_dJ

tensor(-0.2536)

In [16]:
dz_dw = delta_z_delta_w(first_x)
dw_dJ = dz_dw*dz_dJ
dw_dJ

dj_dsig*dsig_dz*dz_dw

tensor([-0.2539, -0.0761])

In [17]:
w = torch.tensor([.5, .3]).float()
b = torch.tensor(-2.).float()

z = linear_fn(first_x, w, b)
print('z = ', z)
y_hat = activation_fn(z)
print('y_hat = ', y_hat)

z =  tensor(-1.4095)
y_hat =  tensor(0.1963)


In [18]:
dj_dsig = delta_J_delta_sigma(y_hat, first_y)

dJ_dz = delta_sigma_delta(z)*dj_dsig # local_deriv*upstream
dJ_dw = delta_z_delta_w(first_x)*dJ_dz # local_deriv*upstream

dJ_dw

dJ_db = delta_z_delta_b()*dJ_dz
dJ_db

tensor(-0.2536)

In [19]:
w = torch.tensor([.5, .3]).float()
b = torch.tensor(-2.).float()
eta = .0001 # define learning rate
for i in range(20):
    for x, y in zip(X_tensor, y_tensor):
    # forward propagation
        z = linear_fn(w, x, b)
        y_hat = activation_fn(z)

    # backward propagation
        dj_dsig = delta_J_delta_sigma(y_hat, y)
        dJ_dz = delta_sigma_delta(z)*dj_dsig
        dJ_dw = delta_z_delta_w(first_x)*dJ_dz

        dJ_db = delta_z_delta_b()*dJ_dz

    # update params w, b
        w = w - eta*dJ_dw
        b = b - eta*dJ_db

In [20]:
w, b

(tensor([0.5786, 0.3236]), tensor(-1.9215))